% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Feb-2018 01:45:14
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                        
%HVAC
load('thermal.mat')
duct_area1 = duct_area/5;
duct_area2 = duct_area/2;
cabin_volume1 = cabin_volume/5;
heaterArea = duct_area/2;
acArea = duct_area/2;
xareaC = 1/5; 

costPerKWH = 0.12;

% Electrical System
costThresh = 10;


