% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Feb-2018 01:45:14
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                        
%HVAC
load('thermal.mat')

% Electrical System
costPerKWH = 0.12;
costThresh = 1;


